[build]
  functions = "api"
  publish = "site"
  command = "npm run build"

[dev]
  publish = "site"
  framework = "#custom"
  autoLaunch = false
  command = "npm run serve:app"
  targetPort = 8000
  port = 8888
